[package]
name = "matrix_multiply_test"
version = "0.1.0"
authors = ["Emanuel Lima <emanuel-lima@outlook.com>"]
edition = "2018"

[dependencies]
ndarray-rand = "0.12.0"
ndarray = "0.14.0"
rand = "0.7.3"
